### ISSUE TITLE
USER STORY: Navbar

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#1]
Epic:  [Site Navigation](https://github.com/miloszmisiek/ci-p5-cutback/issues/7)

## Description
As a **user** I can **access the site's navigation from every page** so that **I can visit every page quickly all the time**

## Tasks
- [x] Create NavBar component
- [x] Import and use the NavBar component in App.js
- [x] Test NavBar with placeholder
- [x] Create search bar component
- [x] Create categories component
- [x] Create logged-in user dropdown menu
- [x] Create logged-out user buttons (sign in/signup)
---
**Style Navbar with custom CSS**
- [x] Install styled-components
- [x] Arrange directories to include component and styled-components in the same folder
- [x] Style the NavBar for the logged-out user
- [x] Style the NavBar for the logged-in user 
- [x] Style search bar with categories + responsiveness

**Comment by miloszmisiek** [comment]
! **styled-components are implemented for CSS styling**
