### ISSUE TITLE
USER STORY: Navigation, Profile Dropdown List

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#10]
### Description:
As a **user logged-in user** I can **see the Profile dropdown menu in the navbar** so that **I can have access to all relevant profile features from every page**

## Tasks:
- [x] Create a dropdown list for logged-in with user-related links
- [x] Give access to the user's products, and profile from the dropdown
- [x] Display message to indicate currently logged-in user
- [x] Include signout function in dropdown list
- [x] Use the user's profile picture as the dropdown list trigger button
