### ISSUE TITLE
USER STORY: Voting, Like a Product

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#12]
### Description:
As a **logged-in user** I can **rate a product** so that **I can share my experience about a product and position it higher in ranks**

## Tasks:
- [x] Implement a Rating component based on a 5-star rating
- [x] Allow logged-in users to vote and update their ratings on the Product page
- [x] Display ratings on the Product card on the home page
- [x] Display all Ratings and split them into single-star counter
