### ISSUE TITLE
USER STORY: Create products

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#16]
## Epic 
[The Products Page](https://github.com/miloszmisiek/ci-p5-cutback/issues/15)

## Description
As a **logged-in user** I can **create products** so that **notice other users about my gear offer**

## Tasks:
- [x] Create CreateProductForm component with styling
- [x] Create ProductGallery component with styling
- [x] Include ProductGallery component in CreateProductForm component.
- [x] Display default picture if no product gallery is empty
- [x] Create thumbnails of added images.
- [x] Create an image preview with thumbnails of the selected image.
- [x] Include fields required for submitting Product
- [x] Display spinner for fields with API waiting time.
- [x] Include product images with the product's submission functionality.
- [x] Functionality for adding and deleting images.
