### ISSUE TITLE
USER STORY: Edit Product

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#18]
## Epic
[The Product Page](https://github.com/miloszmisiek/ci-p5-cutback/issues/15)

## Description
As an **owner of the product** I can **edit product details** so that **I can guarantee that the product details are latest and up-to-date**

## Tasks:
- [x] Fetch data for product ID included in the URL
- [x] Add spinner for API response waiting.
- [x] Include values from API data in the form.
- [x] Create Delete product functionality.
- [x] Create Modal component for defensive programming usage with delete functionality
