### ISSUE TITLE
USER STORY: Delete the product

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#19]
## Epic
[The Products Page](https://github.com/miloszmisiek/ci-p5-cutback/issues/15)

## Description
As an **owner of the product** I can **delete my products** so that **I can control what products am I displaying as an offer**

## Tasks:
- [x] Create separate delete buttons for product images and product instances with respective functionalities.
- [x] Use modal for defensive programming with delete functionality to confirm the user's choice.
- [x] Fetch API delete call on product and product image instances.
- [x] Include Image removal in creating form and edit form
- [x] Include product removal in the edit form.
