### ISSUE TITLE
USER STORY: Authentication, Sign Up

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#2]
## Epic  
[Authentication Process](https://github.com/miloszmisiek/ci-p5-cutback/issues/6)

## Description
As a **user** I can **create a new account** so that **I have access to all features for registered users**

## Tasks
- [x] Install Axios library for handling API calls
- [x] Setup Axios defaults
- [x] Create SignUpForm component
- [x] Update App.js with Routes for links
- [x] Update Sign Up link with SignUpForm in the render method
- [x] Style SignUpForm component
- [x] Handle form submit with Axios post
- [x] Set background for SignUpForm component on render
### Tests
---
- [x] Test form validation
- [x] Test email verification link on submit  
- [x] Test error handling

**Comment by miloszmisiek** [comment]
Closed with all tasks completed
