### ISSUE TITLE
USER STORY: Create a comment

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#21]
## Epic
[Comments Functionality](https://github.com/miloszmisiek/ci-p5-cutback/issues/20)

## Description
As a **logged-in user** I can **post comments on the products** so that **I can share my insights about the product or write a review about the offer**

## Tasks:
- [x] Create a Comment component to be used on the Product page.
- [x] Create Comment creation form component to implement create functionality
- [x] Create a Comment edit component to allow users to edit the comments they own
- [x] Use pagination with comments to restrict data being displayed for better UX
