### ISSUE TITLE
USER STORY: View comments

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#22]
## Epic
[Comments Functionality](https://github.com/miloszmisiek/ci-p5-cutback/issues/20)

## Description
As a **user** I can **read product's comments** so that **I can compare my thoughts about the product with other users**

## Tasks:
- [x] Allow all users to see comments on the Product page
- [x] Display the number of comments on the Product card and on the Product page together with a rating
- [x] Add username and avatar of comment owner together with the created date and comment description
