### ISSUE TITLE
USER STORY: Edit a comment

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#23]
## Epic
[Comments Functionality](https://github.com/miloszmisiek/ci-p5-cutback/issues/20)

## Description
As an **owner of the comment** I can **edit the comment content** so that **I can change it if required**

## Tasks:
- [x] Create an edit comment component to allow users to edit the comments they own
- [x] Implement restriction on editing comments only by owners
- [x] Add the edit comment button to the **more** button next to the owner's comment
