### ISSUE TITLE
USER STORY: Infinite Scroll

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#28]
## Epic
None

## Description
As a **user** I can **explore paginated products from the database** so that **I can focus my attention on the smaller chunks of displayed content**

## Tasks:
- [x] Install React Pagination component for handling site pagination
- [x] Connect backend data pagination with frontend displayed data
- [x] Include pagination for Product's comment section
