### ISSUE TITLE
USER STORY: Authentication, Sign in

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#3]
Epic:  [Authentication Process](https://github.com/miloszmisiek/ci-p5-cutback/issues/6)

### Description
As a **user** I can **sign in to the website** so that **I can use all features for logged-in users**

### Tasks
- [x] Create SignIn component with styling
- [x] Include all sign-in required fields in the form
- [x] Include POST method for login with DRF API
