### ISSUE TITLE
USER STORY: Search Functionality

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#31]
## Epic
[The Products Page](https://github.com/miloszmisiek/ci-p5-cutback/issues/15)

## Description
As a **user** I can **search for products with keywords** so that **I can find offers which I am most interested in**

## Tasks:
- [x] Create a search bar component to allow users to keywords search in the app: **title**, **description**, **username**, **street**, **city**, **country**
- [x] Implement searching "on-change" without the need of submitting a search query with a button
- [x] Implement timeout for product rendering for better UX
