### ISSUE TITLE
USER STORY: Sorting Products

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#32]
## Epic
[The Products Page](https://github.com/miloszmisiek/ci-p5-cutback/issues/15)

## Description
As a **user** I can **sort the products currently displayed** so that **I can see the products in the order I am most interested in**

## Tasks:
- [x] Create filters section with **in stock** and **countries** filtering functionality.
- [x] Create sorting functionality for date created, price, title, average score and all scores options in ascending and descending order
- [x] Create a button to display **all** products without filters applied.
- [x] Create a search bar with a **title**, **description**, **username**, **street**, **city** and **country** options to search for
