### ISSUE TITLE
USER STORY: Categories Selection

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#33]
## Epic
[The Products Page](https://github.com/miloszmisiek/ci-p5-cutback/issues/15)

## Description
As a **user** I can **display products by categories** so that **I can find products of my interest easier**

## Tasks:
- [x] Create a custom hook to fetch categories from the API endpoint
- [x] Create a dropdown menu integrated with the search bar in the navbar
- [x] Display currently select category in the menu
