### ISSUE TITLE
USER STORY: Footer Section

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#34]
## Epic
[Site Navigation](https://github.com/miloszmisiek/ci-p5-cutback/issues/7)

## Description
As a **user** I can **view a footer from every page** so that **I can have easy access to all footer content on different pages**

## Tasks:
- [x] Create a footer component to display creators' social links and app logo
- [x] Add copyright to footer section
- [x] Style footer to remain at the bottom of the page
