### ISSUE TITLE
USER STORY: Products Availability

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#39]
## Epic
[Products Functionality](https://github.com/miloszmisiek/ci-p5-cutback/issues/15)

## Description
As a **user** I can **see if the product is available** so that **I can decide to contact the offer owner**

## Tasks:
- [x] Display availability on the Product page - Available with green, Out of Stock with red colours
- [x] Add Out Of Stock overlay to products not available
- [x] Display by default only available Products
- [x] Allow users to display all products on button click
