### ISSUE TITLE
USER STORY: Products Gallery

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#41]
## Epic
[Products Functionality](https://github.com/miloszmisiek/ci-p5-cutback/issues/15)

## Description
As a **user** I can **see the product pictures** so that **I know what the product looks like in reality**

## Tasks:
- [x] Create gallery thumbnails with a preview window for creating and editing products.
- [x] Create a Carousel component for Product card display and Product page display.
- [x] Disable animation for Product card carousel, enable animation for Product page display
- [x] Add restriction of 5 images per product with the alert display.
- [x] Display the default image if the gallery for the product is empty.
