### ISSUE TITLE
USER STORY: Create the Footer component.

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#43]
## Epic
[Site Navigation](https://github.com/miloszmisiek/ci-p5-cutback/issues/7)

## Description
As a **user** I can **find links to the creator's social media** so that **I can explore the other content created by him/her**.

## Tasks:
- [ ] Create the Footer component file
- [ ] Create the Footer styled-component file
- [ ] Adjust responsiveness for different screen sizes.
- [ ] Test the Footer with jest
- [ ] Describe the manual test performed
