### ISSUE TITLE
USER STORY: Navigation with Routing

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#8]
### Description:
As a **user** I can **navigate through different pages smoothly** so that **I can explore site content without page refreshing**

## Tasks:
- [x] Install React Router library to use as a routing tool
- [x] Include Routes in App.js with correct components to render
- [x] Prevent unnecessary page refresh on form submits with event preventDefault() functions
