### ISSUE TITLE
USER STORY: Navigation, Navbar login buttons

### ISSUE THREAD

**Issue by miloszmisiek** [miloszmisiek/ci-p5-cutback#9]
### Description:
As a **logged-out user** I can **see the sign-in and sign-up buttons** so that **I can change my login status**

## Tasks:
- [x] Create CurrentUserContext with token refresh functionality
- [x] Create Sign-in and Sign-up buttons and add styling
- [x] Include conditional rendering of navbar components for logged-in and logged-out users based on current user status
